// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badil.Backend.Data.Models;

public partial class Product
{
    public long ProductId { get; set; }

    public bool IsBigNameBrand { get; set; }

    public string Barcode { get; set; }

    public string NutriscoreGrade { get; set; }

    public string Brands { get; set; }

    public string Ingredients { get; set; }

    public string Url { get; set; }

    public string Title { get; set; }

    public virtual ICollection<UserReview> UserReviews { get; set; } = new List<UserReview>();

    public virtual ICollection<Product> AlternativeProducts { get; set; } = new List<Product>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}