// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badil.Backend.Data.Models;

public partial class UserReview
{
    public int UserId { get; set; }

    public long ProductId { get; set; }

    public int? Score { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}